# Version of docker-compose
version: '3.2'

# Containers we are going to run
services:
  # Our Phoenix container
  app:
    stdin_open: true
    tty: true
    # The build parameters for this container.
    build: .
    volumes:
      - .:/app:delegated
      - static:/app/priv/static:delegated
      - deps:/app/deps:delegated
      - build:/app/_build:delegated
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chatplayer_prod
      - MIX_ENV=prod
      - PORT=4000
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
  db:
    image: postgres:11.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 54320:5432
    volumes:
      - pgdata:/var/lib/postgresql/data:delegated
# Define the volumes
volumes:
  static:
  deps:
  build:
  pgdata:
