# Version of docker-compose
version: '3.2'

# Containers we are going to run
services:
  # Our Phoenix container
  app:
    stdin_open: true
    tty: true
    # The build parameters for this container.
    build: .
    volumes:
      - .:/app:delegated
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/chatplayer_prod
      # Variables to connect to our Postgres server
      # PGUSER: postgres
      # PGPASSWORD: postgres
      PGDATABASE: chatplayer_prod # only for docker-entrypoint script
      # PGPORT: 5432
      # Hostname of our Postgres container
      # PGHOST: db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
  db:
    image: postgres:11.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 54320:5432
    volumes:
      - pgdata:/var/lib/postgresql/data:delegated
# Define the volumes
volumes:
  pgdata:
